kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  namespace: default
  annotations:
    avp.kubernetes.io/path: "argotest/data/test"
type: Opaque
stringData:
  sample-secret: <sampletest>
